### ISSUE TITLE
dedicated slack channel that can be assumed to be only memo's

### ISSUE THREAD

**Issue by Dieterbe** [raintank/memo#1]
@aocenas suggested this

pro:
* don't need to type 'memo ' prefix anymore
* central channel wherein all changes can be discussed seems useful

con:
* loose a bit of context/scope (with current approach, the channel you use memo in acts as a filter for the scope/project/team), unless you have multiple of these channels
* yet another channel(s)

**Comment by aocenas** [comment]
Just to clarify a bit, in previous work we had a channel where each message was an environment change that was not logged anywhere else (we were only slowly moving towards infra as code so lots of stuff was done through some UI somewhere). Combining such channel with memo and having it shown in dashboards annotations would be pretty useful I think.
