### ISSUE TITLE
Is this repository abandoned?

### ISSUE THREAD

**Issue by julioz** [raintank/memo#21]
Hi,

I'm interesting in experimenting with `memo` but looking around the repository I wonder if it is abandoned.

There are a few GitHub issues open and more importantly the GitHub Action workflow run to publish the latest `main` branch failed.

If it is abandoned, then I suggest updating the README and archiving the repository for future readers' reference.

**Comment by surdaft** [comment]
It is not quite abandoned but there hasn't been much of a requirement to further update the project. :)

**Comment by surdaft** [comment]
I fixed the latest action, there was an issue with the signing process that I didn't have opportunity to fix before. Thanks for the ticket on that. :)

**Comment by julioz** [comment]
Great, thank you @surdaft. That being the case, I will go ahead and experiment setting up `memo` on my org soon :)

**Comment by surdaft** [comment]
Fantastic, any issues then do let me know @julioz
