### ISSUE TITLE
Document installation procedure

### ISSUE THREAD

**Issue by JimboJoe** [raintank/memo#4]
Hello,
Thanks for this project!
I'd like to install it on my server, but I'm not sure what is the shortest procedure. Do you plan to share a binary package and/or document the procedure?
Thanks!

**Comment by Dieterbe** [comment]
fixed by #5 . feel free to reopen if it's still not clear.

**Comment by JimboJoe** [comment]
Thanks!
I tried your procedure:
* I had to set `$GOPATH` variable
* the `go get` commands rise `package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)` and I don't get any binary in the `$HOME/bin` or `$GOPATH/bin` directories.

EDIT: It seems I don't have the right to reopen the issue...
