### ISSUE TITLE
add a LICENSE

### ISSUE THREAD

**Issue by joemiller** [raintank/memo#7]
Please consider adding a license to the repo.

Among other reasons, this will also make the code visible on pkg.go.dev, FWIW

https://pkg.go.dev/github.com/grafana/memo/store?tab=overview#NewGrafana

**Comment by Dieterbe** [comment]
can I leave this with you @RichiH :) this is only a little side project for now

**Comment by RichiH** [comment]
Will do.

CC @mattmendick @DeeGeeGit @gouthamve @Tomica-G as this could be relevant to our incident handling discussion.

**Comment by RichiH** [comment]
CC @bergquist for tactical overview
