### ISSUE TITLE
Feature request: Update to use non-classic slack application permissions

### ISSUE THREAD

**Issue by surdaft** [raintank/memo#9]
I would really like if this could be updated to use the Events API [instead of/as well as] the RTM API. I would love to try and implement this but my GO ability is sketchy.

I am working on attempting this, although I do not have all the requirements needed just yet- eg documented which scopes I need.

Have a working setup of it, will refine what I can and hopefully PR. :)

**Comment by Dieterbe** [comment]
hey @surdaft sorry for going dark on you. what's the benefit of the events api over the rtm api?
and why did you end up closing this?

**Comment by surdaft** [comment]
> hey @surdaft sorry for going dark on you. what's the benefit of the events api over the rtm api?
> and why did you end up closing this?

It's all good! The RTM api from what I could tell was now deprecated or slack seems to be encouraging the use of the events API instead, since the only way to get a bot token that allows RTM is by using a "legacy" bot user.

I eventually closed this though as I don't have enough understanding or time to look into implementing it and felt that the quietness meant it wasn't really a needed functionality anyway.

**Comment by Dieterbe** [comment]
Okay thanks anyway
